#plugin name
name: CustomFieldsSearch
version: 0.2.1

#about this plugin
description: <__trans phrase="A plugin enable to search by CustromFields data.">
author_name: <__trans phrase="toi-planning">
author_link: http://tec.toi-planning.net/
plugin_link: http://tec.toi-planning.net/mt/customfieldssearch/
doc_link: http://tec.toi-planning.net/mt/customfieldssearch#manual

#Localization
l10n_class: CustomFieldsSearch::L10N

# hook
init_request: CustomFieldsSearch::App::init_request

#tag
tags:
    help_url: http://tec.toi-planning.net/mt/customfieldssearch/tags#%t
    block:
        IfCustomFieldsSearchField?: CustomFieldsSearch::Template::ContextHandlers::_hdlr_if_field
        CustomFieldsNoSearch?: CustomFieldsSearch::Template::ContextHandlers::_hdlr_no_search
